/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWarehousingRouteImport } from './routes/services.warehousing'
import { Route as ServicesSeaFreightRouteImport } from './routes/services.sea-freight'
import { Route as ServicesGroupageRouteImport } from './routes/services.groupage'
import { Route as ServicesCustomsClearingRouteImport } from './routes/services.customs-clearing'
import { Route as ServicesAirFreightRouteImport } from './routes/services.air-freight'
import { Route as LanesYiwuToGhanaRouteImport } from './routes/lanes.yiwu-to-ghana'
import { Route as LanesGuangzhouToGhanaRouteImport } from './routes/lanes.guangzhou-to-ghana'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWarehousingRoute = ServicesWarehousingRouteImport.update({
  id: '/services/warehousing',
  path: '/services/warehousing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeaFreightRoute = ServicesSeaFreightRouteImport.update({
  id: '/services/sea-freight',
  path: '/services/sea-freight',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGroupageRoute = ServicesGroupageRouteImport.update({
  id: '/services/groupage',
  path: '/services/groupage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomsClearingRoute = ServicesCustomsClearingRouteImport.update({
  id: '/services/customs-clearing',
  path: '/services/customs-clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirFreightRoute = ServicesAirFreightRouteImport.update({
  id: '/services/air-freight',
  path: '/services/air-freight',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesYiwuToGhanaRoute = LanesYiwuToGhanaRouteImport.update({
  id: '/lanes/yiwu-to-ghana',
  path: '/lanes/yiwu-to-ghana',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesGuangzhouToGhanaRoute = LanesGuangzhouToGhanaRouteImport.update({
  id: '/lanes/guangzhou-to-ghana',
  path: '/lanes/guangzhou-to-ghana',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rates': typeof RatesRoute
  '/schedule': typeof ScheduleRoute
  '/tracking': typeof TrackingRoute
  '/lanes/guangzhou-to-ghana': typeof LanesGuangzhouToGhanaRoute
  '/lanes/yiwu-to-ghana': typeof LanesYiwuToGhanaRoute
  '/services/air-freight': typeof ServicesAirFreightRoute
  '/services/customs-clearing': typeof ServicesCustomsClearingRoute
  '/services/groupage': typeof ServicesGroupageRoute
  '/services/sea-freight': typeof ServicesSeaFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rates': typeof RatesRoute
  '/schedule': typeof ScheduleRoute
  '/tracking': typeof TrackingRoute
  '/lanes/guangzhou-to-ghana': typeof LanesGuangzhouToGhanaRoute
  '/lanes/yiwu-to-ghana': typeof LanesYiwuToGhanaRoute
  '/services/air-freight': typeof ServicesAirFreightRoute
  '/services/customs-clearing': typeof ServicesCustomsClearingRoute
  '/services/groupage': typeof ServicesGroupageRoute
  '/services/sea-freight': typeof ServicesSeaFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/rates': typeof RatesRoute
  '/schedule': typeof ScheduleRoute
  '/tracking': typeof TrackingRoute
  '/lanes/guangzhou-to-ghana': typeof LanesGuangzhouToGhanaRoute
  '/lanes/yiwu-to-ghana': typeof LanesYiwuToGhanaRoute
  '/services/air-freight': typeof ServicesAirFreightRoute
  '/services/customs-clearing': typeof ServicesCustomsClearingRoute
  '/services/groupage': typeof ServicesGroupageRoute
  '/services/sea-freight': typeof ServicesSeaFreightRoute
  '/services/warehousing': typeof ServicesWarehousingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/faq'
    | '/login'
    | '/partners'
    | '/rates'
    | '/schedule'
    | '/tracking'
    | '/lanes/guangzhou-to-ghana'
    | '/lanes/yiwu-to-ghana'
    | '/services/air-freight'
    | '/services/customs-clearing'
    | '/services/groupage'
    | '/services/sea-freight'
    | '/services/warehousing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/faq'
    | '/login'
    | '/partners'
    | '/rates'
    | '/schedule'
    | '/tracking'
    | '/lanes/guangzhou-to-ghana'
    | '/lanes/yiwu-to-ghana'
    | '/services/air-freight'
    | '/services/customs-clearing'
    | '/services/groupage'
    | '/services/sea-freight'
    | '/services/warehousing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/faq'
    | '/login'
    | '/partners'
    | '/rates'
    | '/schedule'
    | '/tracking'
    | '/lanes/guangzhou-to-ghana'
    | '/lanes/yiwu-to-ghana'
    | '/services/air-freight'
    | '/services/customs-clearing'
    | '/services/groupage'
    | '/services/sea-freight'
    | '/services/warehousing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  RatesRoute: typeof RatesRoute
  ScheduleRoute: typeof ScheduleRoute
  TrackingRoute: typeof TrackingRoute
  LanesGuangzhouToGhanaRoute: typeof LanesGuangzhouToGhanaRoute
  LanesYiwuToGhanaRoute: typeof LanesYiwuToGhanaRoute
  ServicesAirFreightRoute: typeof ServicesAirFreightRoute
  ServicesCustomsClearingRoute: typeof ServicesCustomsClearingRoute
  ServicesGroupageRoute: typeof ServicesGroupageRoute
  ServicesSeaFreightRoute: typeof ServicesSeaFreightRoute
  ServicesWarehousingRoute: typeof ServicesWarehousingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/warehousing': {
      id: '/services/warehousing'
      path: '/services/warehousing'
      fullPath: '/services/warehousing'
      preLoaderRoute: typeof ServicesWarehousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sea-freight': {
      id: '/services/sea-freight'
      path: '/services/sea-freight'
      fullPath: '/services/sea-freight'
      preLoaderRoute: typeof ServicesSeaFreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/groupage': {
      id: '/services/groupage'
      path: '/services/groupage'
      fullPath: '/services/groupage'
      preLoaderRoute: typeof ServicesGroupageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/customs-clearing': {
      id: '/services/customs-clearing'
      path: '/services/customs-clearing'
      fullPath: '/services/customs-clearing'
      preLoaderRoute: typeof ServicesCustomsClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/air-freight': {
      id: '/services/air-freight'
      path: '/services/air-freight'
      fullPath: '/services/air-freight'
      preLoaderRoute: typeof ServicesAirFreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/yiwu-to-ghana': {
      id: '/lanes/yiwu-to-ghana'
      path: '/lanes/yiwu-to-ghana'
      fullPath: '/lanes/yiwu-to-ghana'
      preLoaderRoute: typeof LanesYiwuToGhanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/guangzhou-to-ghana': {
      id: '/lanes/guangzhou-to-ghana'
      path: '/lanes/guangzhou-to-ghana'
      fullPath: '/lanes/guangzhou-to-ghana'
      preLoaderRoute: typeof LanesGuangzhouToGhanaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  RatesRoute: RatesRoute,
  ScheduleRoute: ScheduleRoute,
  TrackingRoute: TrackingRoute,
  LanesGuangzhouToGhanaRoute: LanesGuangzhouToGhanaRoute,
  LanesYiwuToGhanaRoute: LanesYiwuToGhanaRoute,
  ServicesAirFreightRoute: ServicesAirFreightRoute,
  ServicesCustomsClearingRoute: ServicesCustomsClearingRoute,
  ServicesGroupageRoute: ServicesGroupageRoute,
  ServicesSeaFreightRoute: ServicesSeaFreightRoute,
  ServicesWarehousingRoute: ServicesWarehousingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
